# Generated by Django 5.2.8 on 2025-11-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_sending',
            field=models.BooleanField(default=False),
        ),
    ]
