# Generated by Django 5.2.8 on 2025-11-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_is_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
