# Generated by Django 5.2.8 on 2025-11-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='max_repeats',
            field=models.IntegerField(default=1, help_text='Максимальное количество отправок'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_count',
            field=models.IntegerField(default=0, help_text='Счетчик отправок'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_interval_minutes',
            field=models.IntegerField(default=0, help_text='Интервал повторения в минутах (0 - без повторения)'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='groups',
            field=models.ManyToManyField(to='reminders.group'),
        ),
    ]
